FROM node:latest

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

ADD controllers ./
ADD models ./
ADD routes ./
ADD views ./
COPY package.json ./
COPY app.js ./
COPY db.js ./

USER node

RUN npm install

EXPOSE 8080

CMD [ "node", "app.js" ]

