services:
  web-server:
    image: sethconley981/csc581-project-web-server
    ports:
    - "8080:8080"
    restart: on-failure:3

  game-server:
    image: sethconley981/csc581-project-game-server
    ports:
    - "8000:8000"
    restart: on-failure:3
    
  database:
      image: mongo
      ports:
      - "27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: connect4
        MONGO_INITDB_ROOT_PASSWORD: super_secure_password
      logging:
        driver: none
